### ISSUE TITLE
Try to unfuck the mess that is MemoryManager

### ISSUE THREAD

**Issue by resir014** [resir014/screeps#5]
The `MemoryManager` is currently just a bunch of not-DRY-at-all methods and a bunch of hacks put on top of hacks. Let's try to clean it up.

**Comment by ChaoticWeg** [comment]
I'll work on this.

**Comment by resir014** [comment]
As per this commit: https://github.com/resir014/screeps/pull/10/commits/c0a23a0468387486faa0afa85756004d60b866de

For some reason we can't can't do null-checking on `target_repair_site_id`. Well, either that or the fact that obsolete repair site ids might not be nullified. I've put a temporary hack, but if possible, we might want to find a permanent solution.

**Comment by ChaoticWeg** [comment]
Created a new issue #19 for the issue that @resir014 mentioned. Closing this issue in favor of that one.
