### ISSUE TITLE
Improve our creep creator

### ISSUE THREAD

**Issue by resir014** [resir014/screeps#7]
Right now the method of creating a new `create*()` and `*GoToWork()` method every time we add a new role is not even DRY at all. We should create a single `createNewCreep()` and `creepsGoToWork()` that takes a `role: string` parameter we we can work from there.

This new creep creator will also need to support multiple possible body parts. e.g. `[WORK, CARRY, MOVE]` for "emergency mode", `[WORK, WORK, CARRY, CARRY, MOVE]`, if we could create a stronger creep & a certain number of creeps already exists. Or even add another, much stronger one, later on.

The output of creeps would need to be balanced so that we don't end up with a lot of "emergency" creeps after RCL 2.

**Comment by ChaoticWeg** [comment]
Can/should we close issue #6 in favor of this one?

**Comment by resir014** [comment]
Yes, we should. Closing #6 now.

**Comment by resir014** [comment]
Should be fixed in #28. Any more fine-tuning of the body parts can be done outside of this PR/issue thread.
